### ISSUE TITLE
TODO list for webappp plugin

### ISSUE THREAD

**Issue by ralsina** [getnikola/plugins#29]
- [ ] doesn't support 2-part posts
- [ ] doesn't support translations
- [ ] does insecure path manipulations
- [ ] needs docs
- [ ] needs a way to edit configuration
- [ ] doesn't let you add custom metadata
- [x] custom widgets per field
- [ ] recognize and offer our optional metadata
- [x] password protection

**Comment by Kwpolska** [comment]
I’m copying this over to the Comet CMS repo.
